### ISSUE TITLE
[Suggestion]: Description Totem confusion

### ISSUE THREAD

**Issue by SK0R3N** [Akysooo/Test-V9.5#34]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

La description du skill Enhanced Growth porte confusion.

Il mentionne que le totem augmente de x% le nombre de block que le totem fait pousser. Cependant , on est plus pencher à penser que c'est son rayon d'action qui est augmenter , alors que non.

Je propose donc à ce que la description soit du genre " Le paladium dans le totem durera plus de x%"

**Comment by Elysi0o** [comment]
Modification effectuée ! Merci pour ce retour
