### ISSUE TITLE
[Bug]: Soucis de permissions - Interface de quête

### ISSUE THREAD

**Issue by Windjin1** [Akysooo/Test-V9.5#45]
### Pseudo InGame

Windjin

### Que s'est-il passé ?

Impossible d'ouvrir l'interface de quête depuis l'inventaire.
Message dans le chat disant que je n'ai pas la permission

### Rec

x

### Qu'aurait-il dû arriver ?

x

### LOG

x

**Comment by Zeldown** [comment]
La commande vient du palanpc, il faudrait peut être le retirer @Akysooo ?

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
