### ISSUE TITLE
[Bug]: jeter un item en dehors de son inventaire

### ISSUE THREAD

**Issue by F0rtimel** [Akysooo/Test-V9.5#47]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

On ne peut pas jeter un item en dehors de son inventaire en cliquant dehors de son inventaire avec l'item

### Rec

https://www.youtube.com/watch?v=CJE1aeiJ7Zs

### Qu'aurait-il dû arriver ?

Il aurait du pouvoir jeter un item en dehors de son inventaire

**Comment by Zeldown** [comment]
❌ Impossible a fix avant l'open
