### ISSUE TITLE
[Bug]: Bonbon métier sans récompenses ni notif

### ISSUE THREAD

**Issue by WashiPaladium** [Akysooo/Test-V9.5#48]
### Pseudo InGame

WashiGame_

### Que s'est-il passé ?

Lorsque nous mangeons un bonbon de métier, nous n'obtenons ni jeton, ni notifications, ni récompenses (money, trixium, etc)

### Rec

Je n'ai pas de lien

### Qu'aurait-il dû arriver ?

Lors de la consommation d'un bonbon de métier, nous sommes censé obtenir ce qui est mentionné précédemment

**Comment by Zeldown** [comment]
❌ Impossible à reproduire
