### ISSUE TITLE
[Bug]: utilisation cage pet sans être lvl 10 hunter

### ISSUE THREAD

**Issue by blockgu07** [Akysooo/Test-V9.5#50]
### Pseudo InGame

Blockgu

### Que s'est-il passé ?

J'ai pu mettre un bait dans la cage pet que quelqu'un a posé alors que je ne peux pas poser la cage pet étant donner que je n'ai pas le niveau hunter requis 

### Rec

X

**Comment by hjordn** [comment]
Bug corrigé.

Merci pour le report!
