### ISSUE TITLE
[Bug]: Bouton droite de l'inventaire qui se reset après la fermeture du jeu

### ISSUE THREAD

**Issue by WashiPaladium** [Akysooo/Test-V9.5#52]
### Pseudo InGame

WashiGame_

### Que s'est-il passé ?

Lors de la fermeture du jeu, les modifications que nous faisons sur la barre à droite de l'inventaire se reset

### Rec

https://youtu.be/3WNc8owgOKo

### Qu'aurait-il dû arriver ?

Lors de la fermeture du jeu, les modifications que nous faisons sur la barre à droite de l'inventaire devraient rester lors de la réouverture du jeu

**Comment by AugmaTV** [comment]
Je n'arrive pas a reproduire le bug en dev, ca marche bien de mon coté, je pourrais avoir les logs plz ?

**Comment by AugmaTV** [comment]
fixed
